version: "3.2"

services:
    test:
        build:
          context: . #build will happen in same directory as docker-compose.yml
          dockerfile: ./docker/test/Dockerfile
        image: feztheimmigrant/flora_dex_test
        stdin_open: true #docker run -i
        tty: true # docker run -t
        volumes:
            - type: bind
              source: ./
              target: /app/
    data_capture:
        build:
          context: . #build will happen in same directory as docker-compose.yml
          dockerfile: ./docker/data_capture/Dockerfile
        image: feztheimmigrant/flora_dex_data_capture
        stdin_open: true #docker run -i
        tty: true # docker run -t
        volumes:
            - type: bind
              source: ./
              target: /app/
    data_cleaning:
        build:
          context: . #build will happen in same directory as docker-compose.yml
          dockerfile: ./docker/data_cleaning/Dockerfile
        image: feztheimmigrant/flora_dex_data_cleaning
        stdin_open: true #docker run -i
        tty: true # docker run -t
        volumes:
            - type: bind
              source: ./
              target: /app/
    model_creation:
        build:
          context: . #build will happen in same directory as docker-compose.yml
          dockerfile: ./docker/model_creation/Dockerfile
        image: feztheimmigrant/flora_dex_model_creation
        stdin_open: true #docker run -i
        tty: true # docker run -t
        network_mode: "host" 
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
        volumes:
            - type: bind
              source: ./
              target: /tf/notebooks/
              
